language: php
php:
  - 5.6

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard

script: vendor/bin/phpcs --standard=Symfony2 -n src
