language: php
php:
- 5.4
- 5.5
- 5.6

script: phpunit --coverage-text

#script: phpunit Test.php

# env:
#    - SYMFONY_VERSION=3.1.*
#    - SYMFONY_VERSION=dev-master

#  before_script:
#    - composer require symfony/http-foundation:${SYMFONY_VERSION}

#  script: phpunit --coverage-text