
# Client main part

client_home:
    path: /
    defaults: { _controller: ClientBundle:Client:home}

client_show:
    path: /client_show/{id}
    defaults: { _controller: ClientBundle:Client:show}
    requirements:
              id: \d+
client_show_other:
    path: /client_show/{other}
    defaults: { _controller: ClientBundle:Client:home}

client_search:
    path: /client_search/
    defaults: { _controller: ClientBundle:Client:search}

client_add:
    path: /client_add
    defaults: { _controller: ClientBundle:Client:add}

client_del:
    path: /client_del/{id}
    defaults: { _controller: ClientBundle:Client:del}
    requirements:
              id: \d+

client_del_other:
    path: /client_del/{other}
    defaults: { _controller: ClientBundle:Client:home}


# END Client part

# Category part

category_home:
    path: /categories
    defaults: { _controller: ClientBundle:Category:home}

category_show:
    path: /category_show/{id}
    defaults: { _controller: ClientBundle:Category:show}
    requirements:
              id: \d+

category_show_other:
    path: /category_show/{other}
    defaults: { _controller: ClientBundle:Category:home}

category_add:
    path: /category_add
    defaults: { _controller: ClientBundle:Category:add}

category_del:
    path: /category_del/{id}
    defaults: { _controller: ClientBundle:Category:del}
    requirements:
              id: \d+

category_del_other:
    path: /category_del/{other}
    defaults: { _controller: ClientBundle:Category:home}

# End Category part
# Lang part lang

lang_home:
    path: /lang
    defaults: { _controller: ClientBundle:Lang:home}

lang_show:
    path: /lang_show/{id}
    defaults: { _controller: ClientBundle:Lang:show}
    requirements:
              id: \d+

lang_show_other:
    path: /lang_show/{other}
    defaults: { _controller: ClientBundle:Lang:home}

lang_add:
    path: /lang_add
    defaults: { _controller: ClientBundle:Lang:add}

lang_del:
    path: /lang_del/{id}
    defaults: { _controller: ClientBundle:Lang:del}
    requirements:
              id: \d+

lang_del_other:
    path: /lang_del/{other}
    defaults: { _controller: ClientBundle:Lang:home}

# End Lang part

# ContactType part contactType

contacttype_home:
    path: /contacttype
    defaults: { _controller: ClientBundle:ContactType:home}

contacttype_show:
    path: /contacttype_show/{id}
    defaults: { _controller: ClientBundle:ContactType:show}
    requirements:
              id: \d+

contacttype_show_other:
    path: /contacttype_show/{other}
    defaults: { _controller: ClientBundle:ContactType:home}

contacttype_add:
    path: /contactype_add
    defaults: { _controller: ClientBundle:ContactType:add}

contacttype_del:
    path: /contacttype_del/{id}
    defaults: { _controller: ClientBundle:ContactType:del}
    requirements:
              id: \d+

contacttype_del_other:
    path: /contacttype_del/{other}
    defaults: { _controller: ClientBundle:ContactType:home}

# End ContactType part

client_other:
    path: /{ctg}
    defaults: { _controller: ClientBundle:Client:home}
