parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

services:
    client.validator.repository:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.default_entity_manager:getRepository'
        arguments:
            - ClientBundle\Entity\ContactType

    client.contains_checkhaveallcontacttypes_validator:
        class: ClientBundle\Validator\Constraints\ContainsCheckHaveAllContactTypesValidator
        arguments:
            - "@client.validator.repository"
        tags:
            - { name: validator.constraint_validator }



