parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
    validator.check.repository.name: ClientBundle\Entity\ContactType

services:
    client.contains_checkhaveallcontacttypes_validator:
        class: ClientBundle\Validator\Constraints\ContainsCheckHaveAllContactTypesValidator
        arguments: ["@doctrine.orm.entity_manager", "%validator.check.repository.name%"]
        tags:
            - { name: validator.constraint_validator }



