services:
#    client.example:
#        class: ClientBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    client.contains_checkhaveallcontacttypes_validator:
        class: ClientBundle\Validator\Constraints\ContainsCheckHaveAllContactTypesValidator
        tags:
            - { name: validator.constraint_validator }

parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap

